[build]
  functions = "netlify/functions"
  publish = "/"

[[redirects]]
  from = "/oauth2callback"
  to = "/callback.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
